Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-10, with the labels that each got.

#2178 expose an executable 'shelley-test-cluster' which starts an integration test cluster with faucets
  lib/cli/src/Cardano/CLI.hs
  lib/shelley/cardano-wallet.cabal
  lib/shelley/exe/shelley-test-cluster.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/integration/Main.hs
  nix/.stack.nix/cardano-wallet.nix
  nix/haskell.nix
Labels: ADDING FEATURE

#2198 cardano-addresses: 2.0.0 -> 2.1.0
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/cardano-addresses-cli.nix
  nix/.stack.nix/cardano-addresses.nix
  scripts/cardano-node-rev.sh
  stack.yaml
Labels: ADDING FEATURE

#2212 cardano-node: 1.20.0 -> 1.21.1
  .editorconfig
  cabal.project
  cabal.project.freeze
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  nix/.stack.nix/Win32-network.nix
  nix/.stack.nix/byron-spec-chain.nix
  nix/.stack.nix/byron-spec-ledger.nix
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-crypto-test.nix
  nix/.stack.nix/cardano-crypto-wrapper.nix
  nix/.stack.nix/cardano-ledger-test.nix
  nix/.stack.nix/cardano-ledger.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/hedgehog-extras.nix
  nix/.stack.nix/io-sim-classes.nix
  nix/.stack.nix/io-sim.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-backend-trace-forwarder.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/network-mux.nix
  nix/.stack.nix/ntp-client.nix
  nix/.stack.nix/ouroboros-consensus-byron.nix
  nix/.stack.nix/ouroboros-consensus-cardano.nix
  nix/.stack.nix/ouroboros-consensus-shelley.nix
  nix/.stack.nix/ouroboros-consensus.nix
  nix/.stack.nix/ouroboros-network-framework.nix
  nix/.stack.nix/ouroboros-network.nix
  nix/.stack.nix/shelley-spec-ledger-test.nix
  nix/.stack.nix/shelley-spec-ledger.nix
  nix/.stack.nix/shelley-spec-non-integral.nix
  nix/.stack.nix/small-steps-test.nix
  nix/.stack.nix/small-steps.nix
  nix/.stack.nix/tracer-transformers.nix
  nix/.stack.nix/typed-protocols-examples.nix
  nix/.stack.nix/typed-protocols.nix
  nix/haskell.nix
  nix/sources.json
  stack.yaml
Labels: IMPROVEMENT

#2208 Integration test for external transaction from Icarus wallet
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
Labels: IMPROVEMENT

#2219 Return derivation path when answering `isOurs`
  .gitignore
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Jormungandr.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressDerivationPath.json
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressDerivationSegment.json
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionInputTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiDerivationPath.json
  lib/core/test/data/Cardano/Wallet/Api/ApiDerivationSegment.json
  lib/core/test/data/Cardano/Wallet/Api/ApiDerivationType.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTDerivationIndex.json
  lib/core/test/data/icarusDerivationPrefix-v2020-10-07.sqlite
  lib/core/test/data/shelleyDerivationPrefix-v2020-10-07.sqlite
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/MVarSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/RandomSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscoverySpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/shelley/bench/Restore.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2236 Fix network parameters for both byron and shelley eras
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
Labels: RESOLVING ISSUE

#2242 cabal: Add version constraints on generic-lens
  lib/core/cardano-wallet-core.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
Labels: RESOLVING ISSUE

#2252 Note that coin-selection/random not supported for Byron random wallets. + migration test update
  nix/migration-tests.nix
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2254 select coins for delegation simplifications
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
Labels: ADDING FEATURE

#2241 Revise help text for pool metadata source CLI option
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/shelley/exe/cardano-wallet.hs
Labels: IMPROVEMENT

#2255 do not enforce non-empty outputs for unsigned tx
  default.nix
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2244 Add derivation paths to coin selection change outputs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionChangeTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionOutputTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionTestnet0.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2257 API data-types & specifications for arbitrary metadata signing.
  lib/core-integration/src/Test/Integration/Faucet.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Addresses.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Jormungandr.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/ApiSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/JormungandrSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivationSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/text-class/src/Data/Text/Class.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2229 add verification key endpoint
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/Request.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/src/Cardano/Wallet/Unsafe.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiVerificationKey.json
  lib/core/test/data/Cardano/Wallet/Api/ApiVerificationKeyHash.json
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/text-class/src/Data/Text/Class.hs
  lib/text-class/test/unit/Data/Text/ClassSpec.hs
  nix/.stack.nix/cardano-wallet-core-integration.nix
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2273 Fix address prefixes on testnet
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/cardano-wallet-core-integration.nix
Labels: RESOLVING ISSUE

#2275 Testing change in coin selection
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
Labels: IMPROVEMENT

#2167 Add transaction TTL to payments API
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Orphans.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionFeeDataTestnet0.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2283 Add deprecation disclaimer for random wallet restoration
  specifications/api/swagger.yaml
Labels: IMPROVEMENT
