Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-05, with the labels that each got.

#1631 Don't deserialise blocks in the chain sync node client
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
Labels: IMPROVING CODE

#1629 Buildkite: Only update all-tests-pass branch after other steps pass
  .buildkite/nightly.yml
Labels: IMPROVING CODE

#1630 Reduce logging from network layer
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
Labels: IMPROVING CODE

#1625 Better rendering of bech32 error messages
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
Labels: IMPROVING CODE

#1638 Modify docker-compose.yml example so it is possible to run mainnet and testnet interchangeably
  README.md
  docker-compose.yml
Labels: RESOLVING ISSUE

#1636 adjust logging output for the NTP client
  lib/core/src/Network/Ntp.hs
Labels: IMPROVING CODE

#1615 ChainSync Pipelined: moar speed.
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  nix/.stack.nix/cardano-wallet-byron.nix
Labels: IMPROVING CODE

#1635 Prevent bors from merging into any branch except master
  .buildkite/check-bors.sh
  .buildkite/pipeline.yml
Labels: RESOLVING ISSUE

#1639 Post v2020-05-06 updates
  README.md
  nix/migration-tests.nix
Labels: RESOLVING ISSUE

#1645 Import legacy Byron addresses
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Addresses.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/CLI/Addresses.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1643 Add property and fix for markCharsRedAtIndices
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  nix/.stack.nix/cardano-wallet-cli.nix
Labels: IMPROVING CODE

#1654 Testing Support bech32 encoding
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Keys.hs
Labels: IMPROVING CODE

#1660 docker: fix latest tag
  .buildkite/docker-build-push.nix
Labels: BUG:CONFIRMED

#1662 Use port 9090 on migration tests not to interfere with any wallet tests that run on default port
  lib/jormungandr/test/migration/migration-test.hs
  nix/launch-migration-test.sh
Labels: RESOLVING ISSUE

#1665 Pipeline requests near the chain tip too, with care
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Ouroboros/Network/Client/Wallet.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  nix/.stack.nix/cardano-wallet-core.nix
Labels: IMPROVING CODE

#1640 Absorbing cardano addresses - crypto bits
  bors.toml
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Keys.hs
  lib/core/src/Cardano/Byron/Codec/Cbor.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/ByronSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/IcarusSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/ShelleySpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivationSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/RandomSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscoverySpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs
  lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Keys.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Mnemonics.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
Labels: IMPROVING CODE

#1668 Remove 30s timeout in for chain-sync requests
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
  lib/core/src/Ouroboros/Network/Client/Wallet.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
Labels: RESOLVING ISSUE

#1671 Fix non-terminating fromPParams
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
Labels: RESOLVING ISSUE

#1656 Remove xPrvFromStrippedPubXPrvCheckRoundtrip and related
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivationSpec.hs
Labels: IMPROVING CODE

#1667 Fix failing windows tests
  lib/byron/src/Cardano/Wallet/Byron/Launch.hs
  lib/byron/test/data/cardano-node-byron/genesis.yaml
  lib/byron/test/data/cardano-node-byron/node.cert
  lib/byron/test/data/cardano-node-byron/node.config
  lib/byron/test/data/cardano-node-byron/node.key
  lib/byron/test/data/cardano-node-byron/node.topology
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/data/cardano-node-shelley/deleg.counter
  lib/shelley/test/data/cardano-node-shelley/deleg.skey
  lib/shelley/test/data/cardano-node-shelley/deleg.vkey
  lib/shelley/test/data/cardano-node-shelley/genesis.json
  lib/shelley/test/data/cardano-node-shelley/genesis.skey
  lib/shelley/test/data/cardano-node-shelley/genesis.vkey
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/data/cardano-node-shelley/node-kes.skey
  lib/shelley/test/data/cardano-node-shelley/node-kes.vkey
  lib/shelley/test/data/cardano-node-shelley/node-vrf.skey
  lib/shelley/test/data/cardano-node-shelley/node-vrf.vkey
  lib/shelley/test/data/cardano-node-shelley/node.config
  lib/shelley/test/data/cardano-node-shelley/node.opcert
  lib/shelley/test/data/cardano-node-shelley/node.topology
  lib/shelley/test/data/cardano-node-shelley/regenerate.sh
  nix/windows-testing-bundle.nix
Labels: RESOLVING ISSUE

#1669 Prepare room for Shelley addresses
  lib/cli/src/Cardano/CLI.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Jormungandr.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/MVarSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/JormungandrSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivationSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Main.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Keys.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Mnemonics.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Transactions.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
Labels: ADDING FEATURE

#1661 Misc small nix improvements
  .buildkite/pipeline.yml
  bors.toml
  default.nix
  nix/default.nix
  nix/util.nix
  nix/windows-testing-bundle.nix
Labels: RESOLVING ISSUE

#1664 Add sendAll for Byron endpoints
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletMigrationInfo.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletMigrationPostDataTestnet0.json
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1653 Run multiple coin selections to estimate fees
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/CLI/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiFee.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  nix/.stack.nix/cardano-wallet-core.nix
  specifications/api/swagger.yaml
Labels: IMPROVING CODE

#1682 Scenario to illustrate the migration 500 error on Jormungandr
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
Labels: BUG?

#1683 Fix response code for payment-fees in swagger
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#1684 clarify migrate endpoint end-user documentation
  specifications/api/swagger.yaml
Labels: IMPROVING CODE

#1685 Fix Input resolution for inputs only present in db
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
Labels: RESOLVING ISSUE

#1687 Display Shelley migrations in Api doc
  lib/core/src/Cardano/Wallet/Api.hs
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#1673 Add Shelley `TransactionLayer`
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Faucet.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/Faucet.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Mnemonics.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction/Size.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/data/cardano-node-shelley/start.sh
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/cardano-addresses.nix
  nix/.stack.nix/cardano-wallet-core-integration.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
  stack.yaml
Labels: ADDING FEATURE
