Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-07, with the labels that each got.

#1837 Fix TRANS_GET_01
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
Labels: RESOLVING ISSUE

#1830 Add skeleton `retirement` field to `ApiStakePool`.
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiStakePool.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1827 Introduce k parameter
  lib/byron/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkParameters.json
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Client.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1843 Allow coin-selection to carry an extra "reserve input"
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs
  lib/core-integration/src/Test/Integration/Framework/Request.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/LargestFirst.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Migration.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/Fee.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/FeeSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Main.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: ADDING FEATURE

#1850 Make quitting on a non-empty reward account forbidden
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
Labels: RESOLVING ISSUE

#1841 Bump cardano-ledger-specs to include a fix on non-myopic member reward ordering
  README.md
  cardano-1.14.x.yaml
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  nix/.stack.nix/byron-spec-chain.nix
  nix/.stack.nix/byron-spec-ledger.nix
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-crypto-test.nix
  nix/.stack.nix/cardano-crypto-wrapper.nix
  nix/.stack.nix/cardano-ledger-test.nix
  nix/.stack.nix/cardano-ledger.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/shelley-spec-ledger-test.nix
  nix/.stack.nix/shelley-spec-ledger.nix
  nix/.stack.nix/shelley-spec-non-integral.nix
  nix/.stack.nix/small-steps.nix
  nix/sources.json
  stack.yaml
Labels: RESOLVING ISSUE

#1851 Track stake key registrations independently from delegation
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/test/unit/Cardano/Wallet/Byron/NetworkSpec.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: RESOLVING ISSUE

#1859 install a query flag for driving withdrawals creation on Shelley tx
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1860 add default migration for 'desired_pool_number' in protocol params table
  lib/byron/bench/Restore.hs
  lib/byron/src/Cardano/Wallet/Byron.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
Labels: RESOLVING ISSUE

#1862 remove rewards from the available balance
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  specifications/api/swagger.yaml
Labels: IMPROVING CODE

#1871 Modify STAKE_POOL_NEXT_01 not to fail due to inability to spend rewards in Jormungandr
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
Labels: RESOLVING ISSUE

#1829 Begin porting latency benchmark to shelley
  lib/byron/bench/Latency.hs
  lib/byron/cardano-wallet-byron.cabal
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Cardano/Wallet/LatencyBenchShared.hs
  lib/core/src/Network/Wai/Middleware/Logging.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/test/bench/Latency.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-core-integration.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
Labels: IMPROVING CODE

#1891 Support for staging network
  lib/byron/bench/Restore.hs
  lib/byron/src/Cardano/Wallet/Byron/Launch.hs
  lib/byron/src/Cardano/Wallet/Byron/Transaction/Size.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
Labels: RESOLVING ISSUE

#1847 Track Stakepool Retirements in the DB
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/jormungandr/src/Cardano/Pool/Jormungandr/Metrics.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: ADDING FEATURE

#1849 Diverse witnesses in shelley
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Byron/Codec/Cbor.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: ADDING FEATURE

#1899 Enable `STAKE_POOLS_LIST` tests to run in isolation.
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
Labels: IMPROVING CODE

#1898 Simplify Shelley `listPools` operation.
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: IMPROVING CODE

#1845 Add latency benchmark for shelley
  .buildkite/bench-latency.sh
  .weeder.yaml
  lib/byron/cardano-wallet-byron.cabal
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/shelley/bench/Latency.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
  nix/haskell.nix
Labels: IMPROVING CODE

#1908 migration fix
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
Labels: BUG:MINOR

#1910 Bump cardano-node to 1.15.1 tag
  README.md
  nix/sources.json
Labels: ADDING FEATURE

#1797 Implement log rotation in docker-compose file
  docker-compose.yml
Labels: ADDING FEATURE

#1902 Update cardano-addresses dep
  nix/.stack.nix/cardano-addresses.nix
  nix/windows-release.nix
  stack.yaml
Labels: IMPROVING CODE

#1918 chore: Support Jormungandr-based network address validation in Daedalus
  .weeder.yaml
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  nix/.stack.nix/cardano-wallet-jormungandr.nix
Labels: RESOLVING ISSUE

#1916 Handle too small outputs/changes
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
Labels: BUG:MINOR

#1927 unwind input's dust dependence on minimum utxo value
  lib/core/src/Cardano/Wallet.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: BUG:MINOR

#1928 change minimum withdrawal to 1
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  specifications/api/swagger.yaml
Labels: BUG:MINOR

#1931 Basic integration tests for pool registrations and retirements.
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
Labels: IMPROVING CODE

#1934 Fix docker-compose cannot connect to Byron testnet
  docker-compose.yml
Labels: RESOLVING ISSUE

#1913 Prevent staking to a retired pool.
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Pool/Jormungandr/Metrics.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: ADDING FEATURE

#1938 docker: Make latest point to latest shelley image
  .buildkite/docker-build-push.nix
Labels: IMPROVING CODE

#1946 Withdrawals accounted in received side of prefiler
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
Labels: RESOLVING ISSUE

#1945 Exclude retired pools from the `ListStakePools` API function result.
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  lib/shelley/test/integration/Main.hs
Labels: ADDING FEATURE

#1936 Revise data source consolidation for `ListStakePools`.
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiStakePool.json
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Pool/Jormungandr/Metrics.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1961 Handle Network.Socket.connect: resource exhausted exceptions
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: BUG:MAJOR

#1932 Hardfork countdown support
  lib/byron/bench/Restore.hs
  lib/byron/src/Cardano/Wallet/Byron.hs
  lib/byron/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkParameters.json
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Client.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1954 Fix reported amount on incoming transactions carrying withdrawals
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
Labels: RESOLVING ISSUE

#1969 Add more HasCallStack to shelley network layer
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Primitive/SyncProgress.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: BUG:MAJOR

#1943 Improvements to slotting conversions / TimeInterpreter
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/core/src/Cardano/Wallet/Primitive/SyncProgress.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SlottingSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SyncProgressSpec.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#1972 Fix nightly shelley latency benchmark
  nix/haskell.nix
Labels: RESOLVING ISSUE

#1884 SMASH Integration
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Pool/Metadata.hs
  lib/core/unit.svg
  lib/shelley/bench/Latency.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/exe/cardano-wallet-shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  lib/shelley/test/integration/Main.hs
  nix/.stack.nix/cardano-wallet-cli.nix
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: ADDING FEATURE

#1982 Don't fetch nOpt another time
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: IMPROVING CODE

#1978 Tweak CLI help for --mainnet
  lib/byron/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
Labels: IMPROVING CODE

#1967 Redeem rewards from another wallet
  lib/byron/src/Cardano/Wallet/Byron.hs
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/integration/Cardano/Wallet/Byron/Faucet.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Faucet.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Jormungandr.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/data/Cardano/Wallet/Api/PostPaymentOrWithdrawalDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostPaymentOrWithdrawalFeeDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionFeeDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostWithdrawalData.json
  lib/core/test/data/Cardano/Wallet/Api/PostWithdrawalFeeData.json
  lib/core/test/data/Cardano/Wallet/Api/SomeByronWalletPostData.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/Faucet.hs
  lib/jormungandr/test/integration/Main.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/shelley-genesis.yaml
  lib/shelley/test/integration/Cardano/Wallet/Shelley/Faucet.hs
  lib/shelley/test/integration/Main.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE
