Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-09, with the labels that each got.

#2079 Get TxMetadata from blocks on chain
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Orphans.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  nix/.stack.nix/cardano-wallet-core.nix
  nix/haskell.nix
Labels: ADDING FEATURE

#2090 Add metadata to transaction layer
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: ADDING FEATURE

#2085 [ADP-416] Allow multiple well-formed values in "/Cardano.Wallet.Api/"…
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/ApiSpec.hs
Labels: IMPROVING CODE

#2093 Swagger adjustment: Supported pool id param is hex or bech32
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2091 Add tx metadata to sqlite database
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
Labels: ADDING FEATURE

#2089 Add TxMetadata to API
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiTTxMetadata.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTransactionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTxMetadata.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2096 Tx metadata API integration tests
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet-core-integration.nix
Labels: ADDING FEATURE

#2110 Tx metadata tests
  lib/core-integration/src/Cardano/Wallet/TransactionSpecShared.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: ADDING FEATURE

#2109 Add a script that prints all TODOs/fixmes in code
  .buildkite/pipeline.yml
  default.nix
  lib/core/src/Cardano/Wallet/Api/Server.hs
  scripts/todo-list.sh
Labels: IMPROVING CODE

#2108 Add unit test for transaction metadata fee calculation
  .buildkite/rebuild.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: ADDING FEATURE

#2100 cardano-node: 1.19.0 -> 1.19.1
  README.md
  cardano-1.19.dev1.yaml
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/Win32-network.nix
  nix/.stack.nix/byron-spec-chain.nix
  nix/.stack.nix/byron-spec-ledger.nix
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-binary-test.nix
  nix/.stack.nix/cardano-binary.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-crypto-class.nix
  nix/.stack.nix/cardano-crypto-praos.nix
  nix/.stack.nix/cardano-crypto-test.nix
  nix/.stack.nix/cardano-crypto-wrapper.nix
  nix/.stack.nix/cardano-ledger-test.nix
  nix/.stack.nix/cardano-ledger.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/cardano-prelude-test.nix
  nix/.stack.nix/cardano-prelude.nix
  nix/.stack.nix/cardano-slotting.nix
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/default.nix
  nix/.stack.nix/goblins.nix
  nix/.stack.nix/io-sim-classes.nix
  nix/.stack.nix/io-sim.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-backend-trace-forwarder.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/network-mux.nix
  nix/.stack.nix/ntp-client.nix
  nix/.stack.nix/ouroboros-consensus-byron.nix
  nix/.stack.nix/ouroboros-consensus-cardano.nix
  nix/.stack.nix/ouroboros-consensus-shelley.nix
  nix/.stack.nix/ouroboros-consensus.nix
  nix/.stack.nix/ouroboros-network-framework.nix
  nix/.stack.nix/ouroboros-network-testing.nix
  nix/.stack.nix/ouroboros-network.nix
  nix/.stack.nix/shelley-spec-ledger-test.nix
  nix/.stack.nix/shelley-spec-ledger.nix
  nix/.stack.nix/shelley-spec-non-integral.nix
  nix/.stack.nix/small-steps-test.nix
  nix/.stack.nix/small-steps.nix
  nix/.stack.nix/tracer-transformers.nix
  nix/.stack.nix/typed-protocols-examples.nix
  nix/.stack.nix/typed-protocols.nix
  nix/sources.json
  stack.yaml
Labels: IMPROVING CODE

#2115 stack.yaml: Completely disable RDRAND support in cryptonite
  nix/.stack.nix/default.nix
  stack.yaml
Labels: IMPROVING CODE

#2116 Improve fee estimation performance / fix accidentally quadratic function
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/Fee.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/RandomSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/FeeSpec.hs
Labels: IMPROVING CODE

#2112 simplify implementation of 'estimateMaxNumberOfInputs' & increase coverage
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: IMPROVING CODE

#2122 More sanity byron random-specific benchmarks post restoration + JSON artifacts
  .buildkite/bench-restore.sh
  lib/core-integration/src/Cardano/Wallet/BenchShared.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/cardano-wallet.cabal
  nix/.stack.nix/cardano-wallet.nix
Labels: IMPROVING CODE

#2117 make sure to provide an upper bound for max inputs when adjusting fees
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Migration.hs
  lib/core/src/Cardano/Wallet/Primitive/Fee.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/MigrationSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/FeeSpec.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: RESOLVING ISSUE

#2128 Address slow fee estimation on Byron wallets
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Migrations.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: IMPROVING CODE

#2111 Faster listing of stake pools.
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/Log.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: IMPROVING CODE

#2121 Fix wallet address pool gap limited to Word8
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/shelley/test/integration/Main.hs
Labels: RESOLVING ISSUE

#2131 Temporarily use metadata revision branch of cardano-api
  lib/cli/cardano-wallet-cli.cabal
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/test/data/Cardano/Wallet/Api/ApiTransactionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostPaymentOrWithdrawalDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostPaymentOrWithdrawalFeeDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionFeeDataTestnet0.json
  lib/core/test/unit/Cardano/Wallet/Gen.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/shelley/cardano-wallet.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  nix/.stack.nix/cardano-addresses-cli.nix
  nix/.stack.nix/cardano-addresses.nix
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/cardano-wallet-cli.nix
  nix/.stack.nix/cardano-wallet-core-integration.nix
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  nix/.stack.nix/cardano-wallet-launcher.nix
  nix/.stack.nix/cardano-wallet-test-utils.nix
  nix/.stack.nix/cardano-wallet.nix
  nix/.stack.nix/text-class.nix
  scripts/make_release.sh
  stack.yaml
Labels: IMPROVING CODE

#1935 Enable minUTxOValue: 1000000 in CI for shelley
  lib/core-integration/src/Test/Integration/Faucet.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Addresses.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Miscellaneous.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Port.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Addresses.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/data/cardano-node-shelley/shelley-genesis.yaml
Labels: IMPROVING CODE

#2146 Fix latency benchmarks after introduction of minUTxOValue in tests
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/shelley/bench/Latency.hs
Labels: RESOLVING ISSUE

#2150 Fix a unit test failing on windows due to illegal filename
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetadataSpec.hs
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/test-utils/src/Test/Utils/FilePath.hs
Labels: RESOLVING ISSUE

#2135 Fix dylib references of bundled programs on macOS
  nix/linux-release.nix
  nix/macos-release.nix
  release.nix
  scripts/check-bundle.rb
Labels: RESOLVING ISSUE

#2143 remove storage of intermediate checkpoints in restore blocks
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: RESOLVING ISSUE

#2147 Use JSON "detailed schema" for API TxMetadata
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiTTxMetadata.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTransactionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTxMetadata.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionDataTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/PostTransactionFeeDataTestnet0.json
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2141 Make Jörmungandr tests pass again
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Byron/Wallets.hs
  lib/jormungandr/test/data/jormungandr/block0.bin
  lib/jormungandr/test/data/jormungandr/genesis.yaml
  lib/jormungandr/test/integration/Main.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
Labels: RESOLVING ISSUE

#2125 CLI: Add option "cardano-wallet transaction create --metadata=JSON"
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  nix/.stack.nix/cardano-wallet-cli.nix
Labels: ADDING FEATURE

#2157 Revise swagger API documentation of TxMetadata
  specifications/api/swagger.yaml
Labels: IMPROVING CODE

#2151 Provide slot number (flat slot) in network information
  lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiBlockReference.json
  lib/core/test/data/Cardano/Wallet/Api/ApiByronWallet.json
  lib/core/test/data/Cardano/Wallet/Api/ApiByronWalletBalance.json
  lib/core/test/data/Cardano/Wallet/Api/ApiByronWalletMigrationInfo.json
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkInformation.json
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkTip.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTimeReference.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTransactionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWallet.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletDelegation.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletDelegationNext.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletDelegationStatus.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletMigrationInfo.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletMigrationPostDataTestnet0lenient.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletMigrationPostDataTestnet0raw.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletPassphrase.json
  lib/core/test/data/Cardano/Wallet/Api/ApiWalletPassphraseInfo.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2171 Fix metadata examples in swagger.yaml
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2173 add fallback for metadata JSON parsing from pre-existing database
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
Labels: RESOLVING ISSUE

#2168 Remove Shelley specific transaction CLI tests from Jormungandr
  lib/jormungandr/test/integration/Main.hs
Labels: RESOLVING ISSUE

#2177 Create API address derivation path type.
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressDerivationPath.json
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressDerivationSegment.json
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressDerivationType.json
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiRelativeAddressIndex.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2184 Allow address inspection via the API
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2185 Make addresses separate category in swagger
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2069 More testing of withListeningSocket
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/test/unit/Cardano/Wallet/Api/ServerSpec.hs
Labels: RESOLVING ISSUE
