Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-12, with the labels that each got.

#2352 Rework slotting functions
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/core/src/Cardano/Wallet/Primitive/SyncProgress.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SlottingSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SyncProgressSpec.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: IMPROVEMENT

#2358 fix 'waitForFree' test in Sqlite.DeleteSpec (increase delay)
  lib/core/test/unit/Cardano/DB/Sqlite/DeleteSpec.hs
Labels: RESOLVING ISSUE

#2286 Add health check
  lib/core/src/Cardano/Pool/Metadata.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiHealthCheck.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTHealthCheckSMASH.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/shelley/exe/cardano-wallet.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2364 SMASH health check integration tests
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2381 make 'role' and 'derivationPathSegment' required path parameters in the API spec.
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2308 Extend seq state
  lib/core-integration/src/Test/Integration/Faucet.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/Scripts.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/shelleyRole-v2020-10-13.sqlite
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDerivation/IcarusSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ScriptsSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
Labels: ADDING FEATURE

#2380 Only show actual metrics in EKG
  lib/cli/src/Cardano/CLI.hs
Labels: IMPROVEMENT

#2377 Fix flaky WAI middleware logging test cases
  lib/core/test/unit/Network/Wai/Middleware/LoggingSpec.hs
  scripts/fluke.sh
Labels: RESOLVING ISSUE

#2387 Refresh and use era parameters using latest era genesis.
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkParameters.json
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/ServerSpec.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SyncProgressSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2403 ADP-626 regression integration test
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
Labels: IMPROVEMENT

#2396 Add postTransaction and postTransTo5Addrs into latency benchmarks
  lib/shelley/bench/Latency.hs
Labels: IMPROVEMENT

#2407 scripts/make_release.sh: automate more
  scripts/make_release.sh
Labels: RESOLVING ISSUE

#2336 Fix cardano-address version info and improve version info script
  nix/haskell.nix
  scripts/cardano-node-rev.sh
  scripts/program-revs.sh
Labels: RESOLVING ISSUE

#2327 Show deposits for fees and transactions
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Tx.hs
  lib/core/src/Cardano/Wallet/Registry.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiCoinSelectionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/ApiDelegationAction.json
  lib/core/test/data/Cardano/Wallet/Api/ApiFee.json
  lib/core/test/data/Cardano/Wallet/Api/ApiTransactionTestnet0.json
  lib/core/test/data/Cardano/Wallet/Api/DelegationActionType.json
  lib/core/test/data/metaFee-v2020-11-26.sqlite
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/RegistrySpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/cardano-wallet.cabal
  lib/shelley/exe/cardano-wallet.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet.nix
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2413 Clarify 'MsgFailedToParseGenesis' with regards to which genesis file is expected.
  lib/shelley/exe/cardano-wallet.hs
Labels: IMPROVEMENT

#2409 Always write log files for tests
  lib/shelley/exe/shelley-test-cluster.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
Labels: IMPROVEMENT
