Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-08, with the labels that each got.

#1995 revised SQL query returning next pool metadata to fetch
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/Metadata.hs
Labels: RESOLVING ISSUE

#1999 docker: add nsswitch.conf to base layer
  nix/docker.nix
Labels: BUG:MINOR, IMPROVING CODE

#2001 review guard condition on self withdrawl redemption
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1695 Add shelley mainnet and testnet to nightly restore tests
  .buildkite/bench-latency.sh
  .buildkite/bench-restore.sh
  .buildkite/nightly.yml
  .weeder.yaml
  lib/byron/bench/Latency.hs
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/src/Cardano/Wallet/Byron/Launch.hs
  lib/byron/test/integration/Main.hs
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Cardano/Wallet/BenchShared.hs
  lib/shelley/bench/Cardano/Wallet/Primitive/AddressDiscovery/Any.hs
  lib/shelley/bench/Cardano/Wallet/Primitive/AddressDiscovery/Any/TH.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-core-integration.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
  nix/haskell.nix
  nix/pkgs.nix
  nix/sources.json
Labels: IMPROVING CODE

#2002 Specify that `payments` should be a non-empty list.
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  specifications/api/swagger.yaml
Labels: IMPROVING CODE

#2003 bump tls' dependency version to include support for TLS-1.3
  lib/core/test/unit/Cardano/Wallet/Api/Server/TlsSpec.hs
  nix/.stack.nix/default.nix
  stack.yaml
Labels: RESOLVING ISSUE

#2008 Provide PoolId to the SMASH url builder
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/Metadata.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: RESOLVING ISSUE

#2010 Yet another fix for reported withdrawals in transactions + underflow in case of key deposit reclaim
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
Labels: RESOLVING ISSUE

#2030 Add benchmark for `RndState` and add non-null tracers in benchmark
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/test/bench/db/Main.hs
  nix/.stack.nix/cardano-wallet-core.nix
Labels: RESOLVING ISSUE

#2024 Add pool DB operation `listRetiredPools`.
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  nix/.stack.nix/cardano-wallet-core.nix
Labels: IMPROVING CODE

#2031 Time LSQ requests (and trace the times)
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
Labels: IMPROVING CODE

#2045 Fix restore bench and docker
  .buildkite/bench-restore.sh
  .buildkite/nightly.yml
  .github/RELEASE_TEMPLATE.md
  nix/docker.nix
Labels: RESOLVING ISSUE

#2033 Mark addresses as used while discovering them.
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/RandomSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscoverySpec.hs
Labels: RESOLVING ISSUE

#2048 Adjust travis deployment for renamed cardano-wallet binary
  .travis.yml
  scripts/travis-download-builds.js
Labels: IMPROVING CODE

#2038 Add pool DB operation `removePools`
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/core/test/unit/Cardano/Pool/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
Labels: IMPROVING CODE

#2053 Use ? placeholder syntax in `listRetiredPools`.
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
Labels: IMPROVING CODE

#2036 cardano-node: 1.18.0 -> 1.19.0
  cardano-1.19.x.yaml
  lib/core/src/Cardano/Wallet/Orphans.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  nix/.stack.nix/Win32-network.nix
  nix/.stack.nix/byron-spec-chain.nix
  nix/.stack.nix/byron-spec-ledger.nix
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-binary-test.nix
  nix/.stack.nix/cardano-binary.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-crypto-class.nix
  nix/.stack.nix/cardano-crypto-praos.nix
  nix/.stack.nix/cardano-crypto-test.nix
  nix/.stack.nix/cardano-crypto-wrapper.nix
  nix/.stack.nix/cardano-ledger-test.nix
  nix/.stack.nix/cardano-ledger.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/cardano-prelude-test.nix
  nix/.stack.nix/cardano-prelude.nix
  nix/.stack.nix/cardano-slotting.nix
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/default.nix
  nix/.stack.nix/goblins.nix
  nix/.stack.nix/io-sim-classes.nix
  nix/.stack.nix/io-sim.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-backend-trace-forwarder.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/network-mux.nix
  nix/.stack.nix/ntp-client.nix
  nix/.stack.nix/ouroboros-consensus-byron.nix
  nix/.stack.nix/ouroboros-consensus-byronspec.nix
  nix/.stack.nix/ouroboros-consensus-cardano.nix
  nix/.stack.nix/ouroboros-consensus-mock.nix
  nix/.stack.nix/ouroboros-consensus-shelley.nix
  nix/.stack.nix/ouroboros-consensus-test-infra.nix
  nix/.stack.nix/ouroboros-consensus.nix
  nix/.stack.nix/ouroboros-network-framework.nix
  nix/.stack.nix/ouroboros-network-testing.nix
  nix/.stack.nix/ouroboros-network.nix
  nix/.stack.nix/shelley-spec-ledger-test.nix
  nix/.stack.nix/shelley-spec-ledger.nix
  nix/.stack.nix/shelley-spec-non-integral.nix
  nix/.stack.nix/small-steps-test.nix
  nix/.stack.nix/small-steps.nix
  nix/.stack.nix/tracer-transformers.nix
  nix/.stack.nix/typed-protocols-examples.nix
  nix/.stack.nix/typed-protocols.nix
  nix/haskell.nix
  nix/pkgs.nix
  nix/sources.json
  stack.yaml
Labels: IMPROVING CODE

#2037 Fix stack --nix build
  nix/stack-shell.nix
Labels: RESOLVING ISSUE

#2034 Call getAccountBalance for all wallets at once on tip change
  lib/shelley/cardano-wallet.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-wallet.nix
Labels: RESOLVING ISSUE

#2047 Add pool DB operation `removeRetiredPools`.
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/Log.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/core/test/unit/Cardano/Pool/DB/SqliteSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: IMPROVING CODE

#2054 bump wallet versions tested for migrations to the last 10 releases.
  nix/migration-tests.nix
Labels: RESOLVING ISSUE

#2050 Increase the maximum address pool gap to 100 000
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2068 Update wallet version compatibility table in README
  README.md
Labels: IMPROVING CODE

#2046 use hardfork infrastructure in latency
  lib/shelley/bench/Latency.hs
  nix/haskell.nix
Labels: RESOLVING ISSUE

#2081 Extend restoration benchmarks to include large random wallets.
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/shelley/bench/Restore.hs
Labels: RESOLVING ISSUE

#2071 Minor nix cleanups
  nix/haskell.nix
  nix/migration-tests.nix
Labels: IMPROVING CODE
