Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-11, with the labels that each got.

#2225 Testing pool fetching runtime selection
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Settings.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2293 Revise API error codes
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2253 ADP-494 - Add POST endpoint for script address
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/AnyAddress.json
  lib/core/test/data/Cardano/Wallet/Api/ApiAddressData.json
  lib/core/test/data/Cardano/Wallet/Api/ApiCredential.json
  lib/core/test/unit/Cardano/Wallet/Api/Malformed.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  nix/.stack.nix/cardano-addresses-cli.nix
  nix/.stack.nix/cardano-addresses.nix
  nix/.stack.nix/cardano-wallet-core.nix
  specifications/api/swagger.yaml
  stack.yaml
Labels: ADDING FEATURE

#2300 Make nix-shell evaluation faster
  .envrc
  .gitattributes
  .gitignore
  cabal-nix.project
  default.nix
  nix/haskell.nix
  nix/hls.nix
  nix/materialized/cabal/.plan.nix/cabal-install.nix
  nix/materialized/cabal/default.nix
  nix/materialized/haskell-language-server/.plan.nix/brittany.nix
  nix/materialized/haskell-language-server/.plan.nix/ghcide.nix
  nix/materialized/haskell-language-server/.plan.nix/haskell-language-server.nix
  nix/materialized/haskell-language-server/.plan.nix/hls-plugin-api.nix
  nix/materialized/haskell-language-server/default.nix
  nix/materialized/hlint/.plan.nix/hlint.nix
  nix/materialized/hlint/default.nix
  nix/materialized/hoogle/.plan.nix/hoogle.nix
  nix/materialized/hoogle/default.nix
  nix/materialized/lentil/.plan.nix/lentil.nix
  nix/materialized/lentil/default.nix
  nix/materialized/stylish-haskell/.plan.nix/stylish-haskell.nix
  nix/materialized/stylish-haskell/default.nix
  nix/materialized/weeder/.plan.nix/weeder.nix
  nix/materialized/weeder/default.nix
  nix/sources.json
  shell.nix
Labels: RESOLVING ISSUE

#2246 Get epoch and slot lengths from HFC History Interpreter
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Slotting.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SlottingSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/SyncProgressSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Client.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs
  lib/jormungandr/test/integration/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: RESOLVING ISSUE

#2262 Allow deleting expired transactions from the API
  lib/core-integration/src/Test/Integration/Framework/TestData.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Transactions.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#2289 Use openapi3 for schema tests
  cabal.project
  cabal.project.freeze
  lib/core/cardano-wallet-core.cabal
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/ApiSpec.hs
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  nix/.stack.nix/default.nix
  specifications/api/swagger.yaml
  stack.yaml
Labels: IMPROVEMENT

#2314 Testing maintenance actions
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Settings.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
Labels: ADDING FEATURE

#2318 Additional tweaks with regards to static address construction via the API
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiVerificationKey.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT

#2267 Add CLI option for transaction TTL
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet/Primitive/SyncProgress.hs
  lib/jormungandr/exe/cardano-wallet-jormungandr.hs
  lib/text-class/src/Data/Text/Class.hs
  lib/text-class/test/unit/Data/Text/ClassSpec.hs
  lib/text-class/text-class.cabal
  nix/.stack.nix/cardano-wallet-cli.nix
  nix/.stack.nix/text-class.nix
Labels: ADDING FEATURE

#2330 Integration test: Delegating addresses API roundtrip
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
Labels: IMPROVEMENT

#2335 Move selected primitive types to dedicated modules (Part 2).
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Jormungandr.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/LargestFirst.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Migration.hs
  lib/core/src/Cardano/Wallet/Primitive/CoinSelection/Random.hs
  lib/core/src/Cardano/Wallet/Primitive/Fee.hs
  lib/core/src/Cardano/Wallet/Primitive/Model.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Address.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/ChimericAccount.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Hash.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/RewardAccount.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Tx.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/UTxO.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/ApiSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/LargestFirstSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/MigrationSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelectionSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/FeeSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ModelSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/Types/HashSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: IMPROVEMENT

#2341 Fix for Sqlite DB property tests timeout
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
Labels: RESOLVING ISSUE

#2354 Make sure that db-properties generators and shrinker are somewhat reasonable
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
Labels: IMPROVEMENT

#2301 Reduce nix-shell eval memory usage
  .buildkite/default.nix
  .gitignore
  default.nix
  nix/cabal-shell.nix
  nix/cardano-node-overlay.nix
  nix/default.nix
  nix/haskell.nix
  nix/materialized/cabal/default.nix
  nix/materialized/haskell-language-server/.plan.nix/ghcide.nix
  nix/materialized/haskell-language-server/.plan.nix/haskell-language-server.nix
  nix/materialized/haskell-language-server/.plan.nix/hie-bios.nix
  nix/materialized/haskell-language-server/.plan.nix/hie-compat.nix
  nix/materialized/haskell-language-server/.plan.nix/hls-hlint-plugin.nix
  nix/materialized/haskell-language-server/.plan.nix/hls-plugin-api.nix
  nix/materialized/haskell-language-server/.plan.nix/hls-tactics-plugin.nix
  nix/materialized/haskell-language-server/default.nix
  nix/materialized/hlint/default.nix
  nix/materialized/hoogle/default.nix
  nix/materialized/lentil/.plan.nix/lentil.nix
  nix/materialized/lentil/default.nix
  nix/materialized/stylish-haskell/default.nix
  nix/materialized/weeder/default.nix
  nix/package-cardano-node.nix
  nix/pkgs.nix
  nix/sources.json
  nix/sources.nix
  release.nix
  scripts/gen-hie.sh
  scripts/travis-download-builds.js
  shell.nix
Labels: RESOLVING ISSUE
