Repository cardano-foundation/cardano-wallet, pull requests merged in 2020-06, with the labels that each got.

#1703 Piotr/testing shelley transactions
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/HWWallets.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
Labels: BUG?

#1717 Replace 'Maybe Bool' with a dedicated sum-type.
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
Labels: RESOLVING ISSUE

#1711 Rewrite BYRON_MIGRATE_05 to try to migrate to different addresses (sh…
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/Transactions.hs
Labels: RESOLVING ISSUE

#1725 Report live value of decentralization parameter d.
  lib/byron/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/NetworkSpec.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Pool/Jormungandr/Metrics.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: ADDING FEATURE

#1728 Remove a duplicated comment section.
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
Labels: IMPROVING CODE

#1722 Join stake pool shelley
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation.hs
  lib/core/src/Cardano/Wallet/Primitive/Fee.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
Labels: ADDING FEATURE

#1739 Migration tests clean up
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/test/integration/Main.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Migrations.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Migrations.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/jormungandr/test/integration/Main.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
Labels: IMPROVING CODE

#1735 Clean up old TxParameters SQL table
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
Labels: IMPROVING CODE

#1744 Add api swagger spec for shelley stake pools
  lib/byron/src/Cardano/Wallet/Byron.hs
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiJormungandrStakePoolMetrics.json
  lib/core/test/data/Cardano/Wallet/Api/ApiStakePool.json
  lib/core/test/data/Cardano/Wallet/Api/ApiStakePoolMetrics.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/ApiSpec.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/jormungandr/test/bench/Latency.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1746 encode shelley addresses with their final encoding (bech32 / base58)
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/CompatibilitySpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: ADDING FEATURE

#1776 Fetch metadata discovered on-chain from remote-peers
  lib/byron/cardano-wallet-byron.cabal
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Pool/Metadata.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Byron.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Shelley.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/src/Crypto/Hash/Utils.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/BinarySpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  nix/.stack.nix/cardano-wallet-byron.nix
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
Labels: ADDING FEATURE

#1766 Implement decode signed tx in shelley
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: ADDING FEATURE

#1777 Minimal self-contained docker image
  nix/Dockerfile
  nix/package-cardano-node.nix
  nix/package-jormungandr.nix
  release.nix
Labels: ADDING FEATURE

#1772 More integration test cluster logging improvements
  lib/launcher/cardano-wallet-launcher.cabal
  lib/launcher/src/Cardano/Launcher.hs
  lib/launcher/src/Cardano/Launcher/Node.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/data/cardano-node-shelley/node.config
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-api.nix
  nix/.stack.nix/cardano-cli.nix
  nix/.stack.nix/cardano-config.nix
  nix/.stack.nix/cardano-node.nix
  nix/.stack.nix/cardano-wallet-launcher.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
  nix/.stack.nix/contra-tracer.nix
  nix/.stack.nix/iohk-monitoring.nix
  nix/.stack.nix/lobemo-backend-aggregation.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-monitoring.nix
  nix/.stack.nix/lobemo-backend-trace-forwarder.nix
  nix/.stack.nix/lobemo-scribe-systemd.nix
  nix/.stack.nix/tracer-transformers.nix
  nix/sources.json
  snapshot.yaml
Labels: RESOLVING ISSUE

#1780 re-use optparse applicative definitions from cardano-addresses
  .weeder.yaml
  lib/byron/exe/cardano-wallet-byron.hs
  lib/byron/test/integration/Main.hs
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Keys.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Mnemonics.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Port.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/test/bench/Latency.hs
  lib/jormungandr/test/integration/Main.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Keys.hs
  lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/CLI/Mnemonics.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  nix/.stack.nix/cardano-addresses.nix
  nix/.stack.nix/cardano-wallet-cli.nix
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  stack.yaml
Labels: IMPROVING CODE

#1764 Implement the estimation of maximum number of inputs for Shelley and show big wallet migration
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Migrations.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  nix/.stack.nix/cardano-wallet-shelley.nix
Labels: RESOLVING ISSUE

#1769 Use and combine chain data with LSQ data for stake pools
  lib/core-integration/cardano-wallet-core-integration.cabal
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/shelley/cardano-wallet-shelley.cabal
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  nix/.stack.nix/cardano-wallet-core-integration.nix
  nix/.stack.nix/cardano-wallet-shelley.nix
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1786 Fix windows tests
  .buildkite/nightly.yml
  .buildkite/push-branch.sh
  .github/workflows/ci.yml
  lib/jormungandr/test/data/Cardano-jormungandr/Wallet/Api/ApiAddressTestnet0.json
  lib/jormungandr/test/data/Cardano-jormungandr/Wallet/Api/ApiStakePool.json
  lib/jormungandr/test/data/Cardano-jormungandr/Wallet/Api/ApiStakePoolMetrics.json
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/ApiSpec.hs
  lib/test-utils/src/Test/Utils/Paths.hs
Labels: hydra-dont-build

#1790 Fix logging in shelley integration test cluster
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/test/data/cardano-node-shelley/node.config
Labels: RESOLVING ISSUE

#1795 Get tx by id
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/cli/src/Cardano/CLI.hs
  lib/cli/test/unit/Cardano/CLISpec.hs
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api.hs
  lib/core/src/Cardano/Wallet/Api/Client.hs
  lib/core/src/Cardano/Wallet/Api/Link.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1798 Fix pool listing on testnet
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Pool/Metadata.hs
  lib/core/src/Cardano/Wallet/Api/Server/Tls.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  nix/.stack.nix/cardano-wallet-core.nix
Labels: RESOLVING ISSUE

#1800 wire pool's 'pledge' from the registration certificate unto the Api
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiStakePool.json
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/jormungandr/src/Cardano/Pool/Jormungandr/Metrics.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: ADDING FEATURE

#1804 Add transaction get by id check to Byron API and CLI tests
  lib/byron/test/integration/Test/Integration/Byron/Scenario/API/Transactions.hs
  lib/byron/test/integration/Test/Integration/Byron/Scenario/CLI/Transactions.hs
Labels: IMPROVING CODE

#1801 Temporarily blacklist bad actors when fetching pools metadata
  lib/core/src/Cardano/Pool/DB.hs
  lib/core/src/Cardano/Pool/DB/MVar.hs
  lib/core/src/Cardano/Pool/DB/Model.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs
  lib/core/test/unit/Cardano/Pool/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Pool/DB/Properties.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
Labels: ADDING FEATURE

#1806 Handle key deposit for Shelley transactions
  lib/byron/src/Cardano/Wallet/Byron/Transaction.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/NetworkSpec.hs
  lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Transaction.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/TransactionSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
Labels: RESOLVING ISSUE

#1807 keep track of the last applied checkpoint in the chain follower
  lib/core/src/Cardano/Wallet/Network.hs
Labels: RESOLVING ISSUE

#1810 discard metadata URL based on their hash, not URLs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
Labels: RESOLVING ISSUE

#1768 Store delegation reward account balances in the database
  .buildkite/push-branch.sh
  lib/byron/src/Cardano/Wallet/Byron.hs
  lib/byron/src/Cardano/Wallet/Byron/Api/Server.hs
  lib/byron/src/Cardano/Wallet/Byron/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Logging.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Registry.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/core/test/unit/Cardano/WalletSpec.hs
  lib/jormungandr/cardano-wallet-jormungandr.cabal
  lib/jormungandr/src/Cardano/Wallet/Jormungandr.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Api/Server.hs
  lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs
  lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/jormungandr/test/unit/Cardano/Pool/Jormungandr/MetricsSpec.hs
  lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/NetworkSpec.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Api/Server.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/data/cardano-node-shelley/genesis.yaml
  lib/shelley/test/data/cardano-node-shelley/node.config
  lib/shelley/test/integration/Main.hs
  nix/.stack.nix/cardano-wallet-jormungandr.nix
  nix/pkgs.nix
Labels: RESOLVING ISSUE

#1783 Test that pools have non-myopic member rewards
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
Labels: IMPROVING CODE
