Repository cardano-foundation/cardano-wallet, pull requests merged in 2021-03, with the labels that each got.

#2508 Introduce separate shared state
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Script.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Shared.hs
  lib/core/src/Cardano/Wallet/Primitive/Scripts.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/Gen.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SharedSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/ScriptsSpec.hs
  lib/shelley/bench/Restore.hs
  nix/.stack.nix/cardano-addresses-cli.nix
  nix/.stack.nix/cardano-addresses.nix
  stack.yaml
Labels: ADDING FEATURE

#2416 Use a single-striped connection pool for each database layer instead of a single shared connection
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/DB/Sqlite.hs
  lib/core/src/Cardano/Pool/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Pool/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/test-utils/src/Test/Hspec/Extra.hs
  lib/test-utils/src/Test/Utils/Resource.hs
  lib/test-utils/test/Test/Hspec/ExtraSpec.hs
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-test-utils.nix
Labels: IMPROVEMENT

#2543 E2E tests on testnet
  .github/workflows/e2e-docker.yml
  .github/workflows/e2e-linux.yml
  .github/workflows/e2e-macos.yml
  .github/workflows/e2e-windows.yml
  .gitignore
  test/e2e/.envrc
  test/e2e/.gitignore
  test/e2e/.rakeTasks
  test/e2e/.rake_tasks~
  test/e2e/.rspec
  test/e2e/Gemfile
  test/e2e/Gemfile.lock
  test/e2e/README.md
  test/e2e/Rakefile
  test/e2e/docker-compose-test.yml
  test/e2e/docker_compose
  test/e2e/env.rb
  test/e2e/fixtures/fixture_wallets.json.gpg
  test/e2e/gemset.nix
  test/e2e/helpers/matchers.rb
  test/e2e/helpers/utils.rb
  test/e2e/regenerate-nix.sh
  test/e2e/run_all_tests
  test/e2e/shell.nix
  test/e2e/spec/byron_spec.rb
  test/e2e/spec/e2e_spec.rb
  test/e2e/spec/misc_spec.rb
  test/e2e/spec/shelley_spec.rb
  test/e2e/spec/spec_helper.rb
Labels: IMPROVEMENT

#2563 Get logs from tests against docker
  .github/workflows/e2e-docker.yml
  test/e2e/.gitignore
  test/e2e/.rakeTasks
  test/e2e/.rake_tasks~
  test/e2e/Rakefile
  test/e2e/docker-compose-test.yml
  test/e2e/helpers/matchers.rb
  test/e2e/helpers/utils.rb
  test/e2e/spec/byron_spec.rb
  test/e2e/spec/e2e_spec.rb
  test/e2e/spec/misc_spec.rb
  test/e2e/spec/shelley_spec.rb
Labels: IMPROVEMENT

#2567 Guard pool metadata fetch result persistence with settings status
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  test/e2e/Rakefile
  test/e2e/env.rb
  test/e2e/spec/e2e_spec.rb
  test/e2e/spec/shelley_spec.rb
Labels: RESOLVING ISSUE

#2577 bump actions/cache to v2.1.4 in e2e workflows
  .github/workflows/e2e-docker.yml
  .github/workflows/e2e-linux.yml
  .github/workflows/e2e-macos.yml
  .github/workflows/e2e-windows.yml
Labels: IMPROVEMENT
