Repository cardano-foundation/cardano-wallet, pull requests merged in 2021-01, with the labels that each got.

#2370 [ADP-500] Change addresses are not listed as soon as a transaction is no longer pending
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Sequential.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/SequentialSpec.hs
Labels: RESOLVING ISSUE

#2412 Fix signal handling in test cluster and integration tests
  lib/launcher/src/Cardano/Startup.hs
  lib/shelley/exe/shelley-test-cluster.hs
  lib/shelley/test/integration/Main.hs
Labels: RESOLVING ISSUE

#2405 Additional checks for input existence in transactions
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
Labels: IMPROVEMENT

#2425 import and create random addresses in the 'pending' set
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Primitive/AddressDiscovery/Random.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/AddressDiscovery/RandomSpec.hs
Labels: RESOLVING ISSUE

#2423 Hardcode stake key deposit values to mainnet/testnet for database migrations
  lib/shelley/src/Cardano/Wallet/Shelley.hs
Labels: RESOLVING ISSUE

#2437 PII warning for metadata in api doc.
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2419 Fix flaky stake pools integration test
  .buildkite/pipeline.yml
  lib/cli/cardano-wallet-cli.cabal
  lib/cli/src/Cardano/CLI.hs
  lib/core-integration/src/Test/Integration/Framework/Context.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/Logging.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/test/unit/Cardano/Wallet/NetworkSpec.hs
  lib/shelley/bench/Latency.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/exe/shelley-test-cluster.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  lib/shelley/test/integration/Main.hs
  nix/.stack.nix/cardano-wallet-cli.nix
  nix/.stack.nix/cardano-wallet-core.nix
  scripts/fluke.sh
  specifications/api/swagger.yaml
Labels: RESOLVING ISSUE

#2421 [ADP 627] Upgrade DB benchmarks
  lib/core/cardano-wallet-core.cabal
  lib/core/test/bench/db/Main.hs
  nix/.stack.nix/cardano-wallet-core.nix
Labels: RESOLVING ISSUE

#2431 Index the wallet's UTxO set by asset type
  lib/core/cardano-wallet-core.cabal
  lib/core/src/Cardano/Wallet/Primitive/Types/Address.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Address/Gen.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Coin.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenBundle.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenMap.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenQuantity.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenQuantity/Gen.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Tx.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/Tx/Gen.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/UTxOIndex.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/UTxOIndex/Internal.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/Types/TokenBundleSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/Types/TokenMapSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/Types/UTxOIndex/TypeErrorSpec.hs
  lib/core/test/unit/Cardano/Wallet/Primitive/Types/UTxOIndexSpec.hs
  lib/strict-non-empty-containers/src/Data/Map/Strict/NonEmptyMap/Internal.hs
  lib/strict-non-empty-containers/src/Data/Set/Strict/NonEmptySet.hs
  lib/strict-non-empty-containers/strict-non-empty-containers.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/test-utils/src/Test/Utils/Laws/PartialOrd.hs
  nix/.stack.nix/cardano-wallet-core.nix
  nix/.stack.nix/cardano-wallet-test-utils.nix
Labels: IMPROVEMENT

#2444 Fix yq in travis
  .travis.yml
Labels: RESOLVING ISSUE

#2438 Make hard fork era configurable in local test cluster
  lib/core-integration/src/Cardano/Wallet/BenchShared.hs
  lib/launcher/src/Cardano/Launcher/Node.hs
  lib/shelley/bench/Latency.hs
  lib/shelley/bench/Restore.hs
  lib/shelley/cardano-wallet.cabal
  lib/shelley/exe/cardano-wallet.hs
  lib/shelley/exe/local-cluster.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Launch/Cluster.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/test/data/cardano-node-shelley/node.config
  lib/shelley/test/integration/Main.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  nix/.stack.nix/cardano-wallet.nix
  nix/haskell.nix
Labels: ADDING FEATURE

#2452 Fix some integration tests
  lib/core-integration/src/Test/Integration/Framework/DSL.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Wallets.hs
Labels: RESOLVING ISSUE

#2449 Re-write LocalStateQuery client logic to eliminate acquire failures
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Ouroboros/Network/Client/Wallet.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
Labels: RESOLVING ISSUE

#2461 Add function `computeMinimumAdaQuantity`.
  .stylish-haskell.yaml
  lib/core/src/Cardano/Wallet/Primitive/Types/Coin/Gen.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenBundle.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenMap.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenMap/Gen.hs
  lib/core/src/Cardano/Wallet/Primitive/Types/TokenPolicy/Gen.hs
  lib/shelley/cardano-wallet.cabal
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility/Ledger.hs
  lib/shelley/test/unit/Cardano/Wallet/Shelley/Compatibility/LedgerSpec.hs
  nix/.stack.nix/cardano-wallet.nix
Labels: ADDING FEATURE

#2468 Replace `hardfork_at` with `eras` object, and add node_era
  lib/core-integration/src/Test/Integration/Scenario/API/Network.hs
  lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/core/src/Cardano/Wallet.hs
  lib/core/src/Cardano/Wallet/Api/Server.hs
  lib/core/src/Cardano/Wallet/Api/Types.hs
  lib/core/src/Cardano/Wallet/DB.hs
  lib/core/src/Cardano/Wallet/DB/MVar.hs
  lib/core/src/Cardano/Wallet/DB/Model.hs
  lib/core/src/Cardano/Wallet/DB/Sqlite.hs
  lib/core/src/Cardano/Wallet/Network.hs
  lib/core/src/Cardano/Wallet/Primitive/Types.hs
  lib/core/test/bench/db/Main.hs
  lib/core/test/data/Cardano/Wallet/Api/ApiEra.json
  lib/core/test/data/Cardano/Wallet/Api/ApiEraInfo.json
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkInformation.json
  lib/core/test/data/Cardano/Wallet/Api/ApiNetworkParameters.json
  lib/core/test/shared/Cardano/Wallet/DummyTarget/Primitive/Types.hs
  lib/core/test/unit/Cardano/Wallet/Api/ServerSpec.hs
  lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/Arbitrary.hs
  lib/core/test/unit/Cardano/Wallet/DB/Properties.hs
  lib/core/test/unit/Cardano/Wallet/DB/SqliteSpec.hs
  lib/core/test/unit/Cardano/Wallet/DB/StateMachine.hs
  lib/shelley/src/Cardano/Wallet/Byron/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Compatibility.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Network.hs
  lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs
  specifications/api/swagger.yaml
Labels: IMPROVEMENT
