Repository cardano-foundation/cardano-wallet, pull requests merged in 2024-08, with the labels that each got.

#4711 [ADP-3339] Prepare UI server support
  .buildkite/pipeline.yml
  lib/api/cardano-wallet-api.cabal
  lib/api/src/Cardano/Wallet/Api/Http/Logging.hs
  lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs
  lib/benchmarks/exe/latency-bench.hs
  lib/exe/app/cardano-wallet.hs
  lib/exe/cardano-wallet-exe.cabal
  lib/exe/lib/Cardano/Wallet/Application.hs
  lib/exe/lib/Cardano/Wallet/Application/CLI.hs
  lib/exe/lib/Cardano/Wallet/Application/Logging.hs
  lib/exe/lib/Cardano/Wallet/Application/Server.hs
  lib/exe/lib/Cardano/Wallet/Application/Tls.hs
  lib/exe/lib/Cardano/Wallet/Application/Tracers.hs
  lib/integration/framework/Test/Integration/Framework/Setup.hs
  lib/unit/cardano-wallet-unit.cabal
  lib/unit/test/unit/Cardano/Wallet/Api/ServerSpec.hs
  lib/unit/test/unit/Cardano/Wallet/Application/TlsSpec.hs
  run/common/nix/run.sh
Labels: Deposit, UI

#4717 Fix release pipeline
  scripts/buildkite/release/release-candidate.sh
Labels: CI, Release

#4723 Add nix build to the check nix step
  .buildkite/pipeline.yml
Labels: CI

#4712 [ADP-3339] Add an initial UI service
  cabal.project
  lib/api/cardano-wallet-api.cabal
  lib/api/src/Cardano/Wallet/Api/Http/Server/Handlers/NetworkInformation.hs
  lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs
  lib/api/src/Cardano/Wallet/Api/Types.hs
  lib/api/src/Cardano/Wallet/Api/Types/WalletAssets.hs
  lib/balance-tx/lib/internal/Internal/Cardano/Write/Tx/Balance.hs
  lib/exe/cardano-wallet-exe.cabal
  lib/exe/lib/Cardano/Wallet/Application.hs
  lib/ui/CHANGELOG.md
  lib/ui/LICENSE
  lib/ui/cardano-wallet-ui.cabal
  lib/ui/data/english.txt
  lib/ui/data/images/icon.png
  lib/ui/src/Cardano/Wallet/UI/API.hs
  lib/ui/src/Cardano/Wallet/UI/Cookies.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/Addresses.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/Lib.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/SSE.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/Settings.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/State.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/Wallet.hs
  lib/ui/src/Cardano/Wallet/UI/Handlers/Wallets.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Html.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Htmx.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Lib.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/About.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Addresses.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Lib.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Network.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Page.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Settings.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Template/Footer.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Template/Head.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Template/Navigation.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Wallet.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Wallets.hs
  lib/ui/src/Cardano/Wallet/UI/Html/Pages/Wallets/NewWallet.hs
  lib/ui/src/Cardano/Wallet/UI/Layer.hs
  lib/ui/src/Cardano/Wallet/UI/Lib/ListOf.hs
  lib/ui/src/Cardano/Wallet/UI/Server.hs
  lib/ui/src/Cardano/Wallet/UI/Signal.hs
  lib/ui/test/Main.hs
  run/common/docker/docker-compose.yml
  run/common/docker/run.sh
  run/common/nix/run.sh
Labels: UI

#4724 [ADP-XXX] Cleanup buildkite inter job dependencies
  .buildkite/pipeline.yml
Labels: CI

#4732 [ADP-3407] Cache dev shell nix closure with attic
  .buildkite/pipeline.yml
  docs/site/src/contributor/what/building.md
  docs/site/src/contributor/what/nix.md
  scripts/buildkite/main/attic-cache.sh
Labels: CI

#4734 [ADP-3405] Release v2024-08-11
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-types/delta-types.cabal
  lib/exe/cardano-wallet-exe.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/read/cardano-wallet-read.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet-e2e/cardano-wallet-e2e.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
  specifications/api/swagger.yaml
Labels: Release

#4737 [ADP-3410] Add bump.sh buildkite release steps
  .buildkite/pipeline.yml
  .buildkite/release.yml
  .gitignore
  scripts/buildkite/release/flake.nix
  scripts/buildkite/release/generate-trigger.sh
  scripts/buildkite/release/push-to-bump.sh
  scripts/buildkite/release/release-candidate.sh
  specifications/api/swagger.yaml
Labels: CI, Release

#4739 [ADP-3411] Use nix flake for attic
  .buildkite/pipeline.yml
  scripts/buildkite/main/attic-cache.sh
  scripts/buildkite/main/flake.lock
  scripts/buildkite/main/flake.nix
Labels: CI

#4740 [ADP-3401] Expose the docker image as an artifact
  .buildkite/pipeline.yml
  scripts/buildkite/main/docker-build.sh
Labels: CI, Release

#4733 [ADP-3409] Boostrap mainnet node via mithril
  .buildkite/pipeline.yml
  run/common/docker/run.sh
  run/common/nix/run.sh
  run/mainnet/docker/.env
  run/mainnet/docker/docker-compose.yml
  run/mainnet/nix/.env
Labels: Deposit

#4742 [ADP-3410] Remove bump.sh instructions from github actions
  .github/workflows/release.yml
Labels: CI, Release

#4743 [ADP-xxx] Increase timeout of private newtork syncing steps
  .buildkite/pipeline.yml
Labels: CI

#4744 [ADP-xxx] Add a script to restore shelley and byron preprod wallets
  test/e2e/fixtures/create-wallets.sh
Labels: CI

#4746 [ADP-3409] Expect ready status in nix mithril tests
  .buildkite/pipeline.yml
Labels: CI

#4748 [ADP-3409] Expect ready with mithril and docker
  .buildkite/pipeline.yml
  run/common/docker/run.sh
Labels: CI

#4753 [ADP-3415] Fix ruby e2e to work in any build
  scripts/buildkite/main/linux-e2e.sh
  scripts/buildkite/release/release-candidate.sh
Labels: CI

#4755 [ADP-3414] Optimize benchmark history tracking
  .buildkite/pipeline.yml
  .gitignore
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/benchmarks/exe/benchmark-history.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/History.hs
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/buildkite/src/Buildkite/API.hs
  lib/buildkite/src/Buildkite/Artifacts/CSV.hs
  lib/buildkite/src/Buildkite/Client.hs
  lib/buildkite/src/Buildkite/Connection.hs
  lib/buildkite/src/Buildkite/LimitsLock.hs
  scripts/buildkite/main/benchmark-history.sh
Labels: CI
