Repository cardano-foundation/cardano-wallet, pull requests merged in 2024-02, with the labels that each got.

#4424 [ADP-3266] Add node-to-client-version 15 support
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Shelley.hs
Labels: Conway

#4446 [ADP-3288] Extract benchmark cabal
  cabal.project
  flake.nix
  hie.yaml
  lib/benchmarks/LICENSE
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/benchmarks/exe/EraFun.hs
  lib/benchmarks/exe/api-bench.hs
  lib/benchmarks/exe/db-bench.hs
  lib/benchmarks/exe/latency-bench.hs
  lib/benchmarks/exe/restore-bench.hs
  lib/benchmarks/src/Cardano/Wallet/BenchShared.hs
  lib/benchmarks/src/Cardano/Wallet/LatencyBenchShared.hs
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  nix/haskell.nix
Labels: Refactoring, Conway

#4453 [ADP-3266] Relax eventually and other combinators to work in MonadUnliftIO
  lib/wallet/integration/framework/Test/Integration/Framework/DSL.hs
  lib/wallet/integration/scenarios/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/wallet/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs
  lib/wallet/integration/scenarios/Test/Integration/Scenario/CLI/Byron/Wallets.hs
Labels: CI

#4456 [ADP-3226] Use `bech32` from Hackage.
  cabal.project
Labels: Dependencies

#4447 [ADP-3288] Extract integration cabal
  cabal.project
  flake.nix
  hie.yaml
  justfile
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/integration/exe/integration-tests-exe.hs
  lib/integration/exe/integration-tests.hs
  lib/integration/framework/Test/Integration/Framework/Context.hs
  lib/integration/framework/Test/Integration/Framework/DSL.hs
  lib/integration/framework/Test/Integration/Framework/Logging.hs
  lib/integration/framework/Test/Integration/Framework/PendingInEra.hs
  lib/integration/framework/Test/Integration/Framework/Request.hs
  lib/integration/framework/Test/Integration/Framework/Setup.hs
  lib/integration/framework/Test/Integration/Framework/TestData.hs
  lib/integration/framework/Test/Integration/Plutus.hs
  lib/integration/scenarios/Test/Integration/Run.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Blocks.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/Addresses.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/CoinSelections.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/HWWallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/Migrations.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/Network.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/Transactions.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Byron/Wallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Network.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shared/Addresses.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shared/Transactions.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shared/Wallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Addresses.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/CoinSelections.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/HWWallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Migrations.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Network.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Settings.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/StakePools.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Transactions.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Wallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Byron/Addresses.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Byron/Wallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Miscellaneous.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Network.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Port.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Shelley/Addresses.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Shelley/HWWallets.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Shelley/Transactions.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Shelley/Wallets.hs
  lib/integration/test/data/token-metadata.json
  lib/wallet/cardano-wallet.cabal
Labels: Refactoring

#4421 [ADP-3285] Support sanchonet
  README.md
  configs/cardano/sanchonet/alonzo-genesis.json
  configs/cardano/sanchonet/byron-genesis.json
  configs/cardano/sanchonet/config.json
  configs/cardano/sanchonet/conway-genesis.json
  configs/cardano/sanchonet/db-sync-config.json
  configs/cardano/sanchonet/download.sh
  configs/cardano/sanchonet/shelley-genesis.json
  configs/cardano/sanchonet/submit-api-config.json
  configs/cardano/sanchonet/topology.json
  docker-compose.yml
  scripts/sanchonet.sh
  scripts/sanchonetNix.sh
Labels: Conway

#4463 [ADP-3266] Add manual controls on the nightly pipeline
  .buildkite/nightly.yml
Labels: CI, Conway

#4443 [ADP-3288] Fix latency benchmarks
  justfile
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/benchmarks/exe/latency-bench.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/Latency/BenchM.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/Latency/Measure.hs
  lib/integration/framework/Test/Integration/Framework/DSL.hs
  lib/integration/framework/Test/Integration/Framework/Setup.hs
  lib/local-cluster/lib/Cardano/Wallet/Faucet.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Cluster.hs
  lib/local-cluster/lib/Cardano/Wallet/LocalCluster.hs
  lib/unit/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  lib/wallet/api/http/Cardano/Wallet/Api/Clients/Testnet/Byron.hs
  lib/wallet/api/http/Cardano/Wallet/Api/Clients/Testnet/Network.hs
  lib/wallet/api/http/Cardano/Wallet/Api/Clients/Testnet/Shelley.hs
  lib/wallet/cardano-wallet.cabal
Labels: CI, Conway

#4470 [ADP-0000] Control out of band noise from the node and other sources
  justfile
  lib/benchmarks/exe/latency-bench.hs
  lib/benchmarks/src/Cardano/Wallet/BenchShared.hs
  lib/integration/framework/Test/Integration/Framework/Setup.hs
  lib/launcher/src/Cardano/Launcher/Node.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Cluster.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/ClusterEra.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Config.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/ConfiguredPool.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Faucet.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/NodeParams.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/Relay.hs
  lib/local-cluster/lib/Cardano/Wallet/LocalCluster.hs
  lib/unit/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
  lib/wallet-benchmarks/bench/memory-benchmark.hs
Labels: CI

#4474 [ADP-3304] Fix docker-compose smoke test
  .github/workflows/docker_linux.yml
  configs/cardano/preprod/alonzo-genesis.json
  configs/cardano/preprod/byron-genesis.json
  configs/cardano/preprod/config.json
  configs/cardano/preprod/conway-genesis.json
  configs/cardano/preprod/db-sync-config.json
  configs/cardano/preprod/download.sh
  configs/cardano/preprod/shelley-genesis.json
  configs/cardano/preprod/submit-api-config.json
  configs/cardano/preprod/topology.json
Labels: Bug, CI

#4473 [ADP-3303] Fix quickstart instruction in the README
  README.md
Labels: Bug
