Repository cardano-foundation/cardano-wallet, pull requests merged in 2024-06, with the labels that each got.

#4611 [ADP-3366] Refactor genesis files creation in local cluster
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Aeson.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Cluster.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/GenNodeConfig.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/GenesisFiles.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/NodeParams.hs
  lib/local-cluster/local-cluster.cabal
Labels: Conway

#4615 [ADP-3366] Add era dependency to node config experimental features param
  justfile
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Node/GenNodeConfig.hs
Labels: Conway

#4606 Bump haskellNix and hackage and use hls from hackage
  cabal.project
  flake.lock
  flake.nix
  nix/haskell.nix
Labels: CI

#4617 [ADP-3368] Bump to support node version 8.9.3
  cabal.project
  flake.lock
  flake.nix
  justfile
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/faucet/faucet.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wallet-e2e/cardano-wallet-e2e.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
Labels: Conway

#4620 [ADP-3368] Bump leftover 8.9.2 referiments to 8.9.3
  .github/workflows/docker_linux.yml
  .github/workflows/e2e-docker.yml
  README.md
  scripts/release-candidate.sh
  scripts/sanchonet.sh
  test/e2e/README.md
  test/e2e/docker_compose.sh
Labels: Conway

#4604 [ADP-3305] Use local-cluster executable in integration tests
  .buildkite/pipeline.yml
  justfile
  lib/integration/cardano-wallet-integration.cabal
  lib/integration/framework/Test/Integration/Framework/LocalCluster/SendFaucetAssets.hs
  lib/integration/framework/Test/Integration/Framework/Setup.hs
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/iohk-monitoring-extra/src/Cardano/BM/ToTextTracer.hs
  lib/local-cluster/exe/local-cluster.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/CommandLine.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Http.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Http/Client.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Http/Monitor/Client.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/Monitoring/Phase.hs
  lib/local-cluster/local-cluster.cabal
  lib/local-cluster/process/Cardano/Wallet/Launch/Cluster/Process.hs
  lib/local-cluster/test/unit/Cardano/Wallet/Launch/Cluster/Http/ServiceSpec.hs
  lib/wallet-e2e/src/Cardano/Wallet/Spec/Network/Local.hs
  lib/wallet/src/Cardano/Wallet/Pools.hs
Labels: CI, Deposit

#4624 [ADP-3368] Fix windows e2e suite
  test/e2e/Gemfile
Labels: CI, Conway

#4634 [ADP-3226] drop tests that assume port 8090 is unbound on the host
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Port.hs
Labels: Bug, CI

#4636 [ADP-3368] Add benchmark format and write lib, add csv reporting to benchmarks
  .buildkite/bench-db.sh
  .buildkite/nightly.yml
  .buildkite/pipeline.yml
  justfile
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/benchmarks/exe/api-bench.hs
  lib/benchmarks/exe/db-bench.hs
  lib/benchmarks/exe/latency-bench.hs
  lib/benchmarks/exe/read-blocks.hs
  lib/benchmarks/src/Cardano/Wallet/BenchShared.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/Collect.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/Latency/Measure.hs
  lib/iohk-monitoring-extra/src/Cardano/BM/ToTextTracer.hs
  lib/launcher/src/Cardano/Launcher/Wallet.hs
  lib/local-cluster/exe/local-cluster.hs
  lib/local-cluster/process/Cardano/Wallet/Launch/Cluster/Process.hs
  lib/wallet-benchmarks/bench/memory-benchmark.hs
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet-benchmarks/data/hoogle-pmap.txt
  lib/wallet-benchmarks/lib/Cardano/Wallet/Benchmark/Memory/Pmap.hs
  lib/wallet-benchmarks/test/Cardano/Wallet/Benchmark/Memory/PmapSpec.hs
  lib/wallet-benchmarks/test/Main.hs
Labels: CI

#4635 [ADP-3368] Set all internal packages version to 2024.5.5 or 0.2024.5.5
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/delta-types/delta-types.cabal
  lib/faucet/faucet.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/read/cardano-wallet-read.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-e2e/cardano-wallet-e2e.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
Labels: CI

#4640 [ADP-3368] Update gemset.nix
  test/e2e/Gemfile.lock
  test/e2e/gemset.nix
Labels: CI

#4643 [ADP-3368] Add admin.yml pipeline with a step to update a preprod snapshot
  .buildkite/admin.yml
  scripts/buildkite/release/fetch-preprod-snapshot.sh
Labels: CI

#4644 [ADP-3368] Use flakes in E2E, remove default.nix, shell.nix
  .gitignore
  default.nix
  nix/haskell.nix
  shell.nix
  test/e2e/.envrc
  test/e2e/shell.nix
Labels: CI

#4648 [ADP-3368] Add basic release pipeline
  .buildkite/pipeline.yml
  .buildkite/release.yml
  scripts/buildkite/release/release-candidate.sh
Labels: CI, Release

#4649 [ADP-3368] Add linux packaging step to release pipeline
  .buildkite/release.yml
  scripts/buildkite/release/linux-package.sh
Labels: CI, Release

#4654 [ADP-3368] Add linux E2E step to release pipeline
  .buildkite/release.yml
  scripts/buildkite/release/linux-e2e.sh
  test/e2e/README.md
  test/e2e/Rakefile
  test/e2e/helpers/cardano_cli.rb
  test/e2e/run_all_tests.sh
Labels: CI, Release

#4651 Demonstrate that the HTTP API returns "Internal Server Error" when attempting to encrypt multiple transaction metadata messages.
  lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs
Labels: Bug, DEMONSTRATION
