Repository cardano-foundation/cardano-wallet, pull requests merged in 2024-03, with the labels that each got.

#4479 [ADP-3309] Fix latency benchmark
  lib/address-derivation-discovery/lib/Cardano/Wallet/Address/Discovery.hs
Labels: Bug, CI

#4485 [ADP-3255] Release-candidate/v2024-03-01
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  specifications/api/swagger.yaml
Labels: Conway

#4488 [ADP-3297] Support restoration mode in CLI
  lib/integration/framework/Test/Integration/Framework/DSL.hs
  lib/integration/scenarios/Test/Integration/Scenario/CLI/Port.hs
  lib/unit/test/data/Cardano/CLISpec/wallet create from-recovery-phrase --help
  lib/unit/test/data/Cardano/CLISpec/wallet create from-recovery-phrase from-checkpoint --help
  lib/unit/test/unit/Cardano/CLISpec.hs
  lib/wai-middleware-logging/src/Network/Wai/Middleware/Logging.hs
  lib/wallet/api/http/Cardano/CLI.hs
  lib/wallet/src/Cardano/DB/Sqlite.hs
Labels: ADDING FEATURE

#4497 [ADP-3321] Run read-blocks benchmarks in CI
  .buildkite/bench-read-blocks.sh
  .buildkite/pipeline.yml
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/benchmarks/exe/read-blocks.hs
Labels: CI

#4491 [ADP-3319] Replace implementation of `EraFun`
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Block.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Block/Header.hs
  lib/read/lib/Cardano/Wallet/Read/Eras.hs
  lib/read/lib/Cardano/Wallet/Read/Eras/EraFun.hs
  lib/wallet/api/http/Cardano/Wallet/Api/Http/Server/Handlers/TxCBOR.hs
Labels: Refactoring

#4460 [ADP-3288] Extract `cardano-wallet-api` cabal package
  cabal.project
  docs/site/src/contributor/what/building.md
  flake.nix
  hie.yaml
  lib/api/cardano-wallet-api.cabal
  lib/api/exe/cardano-wallet.hs
  lib/api/src/Cardano/CLI.hs
  lib/api/src/Cardano/Wallet/Api.hs
  lib/api/src/Cardano/Wallet/Api/Aeson.hs
  lib/api/src/Cardano/Wallet/Api/Aeson/Variant.hs
  lib/api/src/Cardano/Wallet/Api/Client.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Byron.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Network.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Shelley.hs
  lib/api/src/Cardano/Wallet/Api/Hex.hs
  lib/api/src/Cardano/Wallet/Api/Http/Logging.hs
  lib/api/src/Cardano/Wallet/Api/Http/Server.hs
  lib/api/src/Cardano/Wallet/Api/Http/Server/Error.hs
  lib/api/src/Cardano/Wallet/Api/Http/Server/Handlers/MintBurn.hs
  lib/api/src/Cardano/Wallet/Api/Http/Server/Handlers/TxCBOR.hs
  lib/api/src/Cardano/Wallet/Api/Http/Server/Tls.hs
  lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs
  lib/api/src/Cardano/Wallet/Api/Lib/ApiAsArray.hs
  lib/api/src/Cardano/Wallet/Api/Lib/ApiT.hs
  lib/api/src/Cardano/Wallet/Api/Lib/ExtendedObject.hs
  lib/api/src/Cardano/Wallet/Api/Lib/Options.hs
  lib/api/src/Cardano/Wallet/Api/Link.hs
  lib/api/src/Cardano/Wallet/Api/Types.hs
  lib/api/src/Cardano/Wallet/Api/Types/Amount.hs
  lib/api/src/Cardano/Wallet/Api/Types/BlockHeader.hs
  lib/api/src/Cardano/Wallet/Api/Types/Certificate.hs
  lib/api/src/Cardano/Wallet/Api/Types/Error.hs
  lib/api/src/Cardano/Wallet/Api/Types/Key.hs
  lib/api/src/Cardano/Wallet/Api/Types/MintBurn.hs
  lib/api/src/Cardano/Wallet/Api/Types/Primitive.hs
  lib/api/src/Cardano/Wallet/Api/Types/RestorationMode.hs
  lib/api/src/Cardano/Wallet/Api/Types/SchemaMetadata.hs
  lib/api/src/Cardano/Wallet/Api/Types/Transaction.hs
  lib/api/src/Cardano/Wallet/Api/Types/WalletAsset.hs
  lib/api/src/Cardano/Wallet/Api/Types/WalletAssets.hs
  lib/api/src/Cardano/Wallet/Shelley.hs
  lib/api/src/Cardano/Wallet/Tracers.hs
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wallet/cardano-wallet.cabal
  nix/haskell.nix
  nix/nixos/cardano-wallet-service.nix
  nix/project-package-list.nix
  nix/release-build.nix
  nix/scripts.nix
  scripts/check-bundle.rb
Labels: CI

#4494 [ADP-3322] Implement `primitiveTx` as a Read function
  lib/primitive/cardano-wallet-primitive.cabal
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Byron.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Allegra.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Alonzo.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Babbage.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Byron.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/CardanoApi.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Conway.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Mary.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Shelley.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Shelley.hs
  lib/wallet/src/Cardano/Wallet/Shelley/Transaction.hs
Labels: Refactoring

#4499 [ADP-3322] Optimize `EraFun` calls
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Block/Header.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Certificates.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/CollateralInputs.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/CollateralOutputs.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/ExtraSigs.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Fee.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Inputs.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Integrity.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Metadata.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Mint.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Outputs.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Validity.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Withdrawals.hs
  lib/read/lib/Cardano/Wallet/Read/Block/Block.hs
  lib/read/lib/Cardano/Wallet/Read/Block/BlockNo.hs
  lib/read/lib/Cardano/Wallet/Read/Block/Gen.hs
  lib/read/lib/Cardano/Wallet/Read/Block/HeaderHash.hs
  lib/read/lib/Cardano/Wallet/Read/Block/SlotNo.hs
  lib/read/lib/Cardano/Wallet/Read/Block/Txs.hs
  lib/read/lib/Cardano/Wallet/Read/Eras/EraValue.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/CBOR.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Certificates.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/CollateralInputs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/CollateralOutputs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/ExtraSigs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Fee.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Gen.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Hash.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Inputs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Integrity.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Metadata.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Mint.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Outputs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/ReferenceInputs.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/ScriptValidity.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Validity.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Withdrawals.hs
  lib/read/lib/Cardano/Wallet/Read/Tx/Witnesses.hs
Labels: Refactoring

#4500 [ADP-3323] Use Read to compute extended Tx
  lib/api/src/Cardano/Wallet/Api/Http/Server/Handlers/TxCBOR.hs
  lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs
  lib/primitive/cardano-wallet-primitive.cabal
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Block.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Allegra.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Alonzo.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Babbage.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/CardanoApi.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Conway.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/Certificates.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Features/WitnessCount.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Mary.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/Shelley.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Read/Tx/TxExtended.hs
  lib/primitive/lib/Cardano/Wallet/Primitive/Types/Tx/TxExtended.hs
  lib/unit/test/unit/Cardano/WalletSpec.hs
  lib/wallet/src/Cardano/Wallet.hs
  lib/wallet/src/Cardano/Wallet/Shelley/Transaction.hs
  lib/wallet/src/Cardano/Wallet/Transaction.hs
Labels: Refactoring

#4496 [ADP-3302] Bump runtime node dependency to 8.9.0
  .github/workflows/docker_linux.yml
  .github/workflows/e2e-docker.yml
  README.md
  scripts/release-candidate.sh
  scripts/sanchonet.sh
  test/e2e/README.md
  test/e2e/docker_compose.sh
Labels: Conway

#4506 [ADP-3254] Generalize the http client to work on all networks
  lib/api/cardano-wallet-api.cabal
  lib/api/src/Cardano/Wallet/Api/Clients/Byron.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Network.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Shelley.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Byron.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Id.hs
  lib/api/src/Cardano/Wallet/Api/Clients/Testnet/Shelley.hs
  lib/benchmarks/exe/latency-bench.hs
  lib/benchmarks/src/Cardano/Wallet/Benchmarks/Latency/BenchM.hs
  lib/integration/framework/Test/Integration/Framework/DSL/Network.hs
  lib/integration/framework/Test/Integration/Framework/DSL/Wallet.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/Restoration.hs
Labels: Refactoring

#4493 [ADP-3320] Create skeleton HTTP API for Deposit Wallet
  lib/customer-deposit-wallet/api/http/Cardano/Wallet/Deposit/HTTP.hs
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP.hs
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP/Endpoints.hs
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP/Implementation.hs
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP/Types/API.hs
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP/Types/JSON.hs
  lib/customer-deposit-wallet/http/Cardano/Wallet/Deposit/HTTP/Types/JSON/Encoding.hs
  lib/customer-deposit-wallet/spec/openapi/HTTP.yaml
  lib/customer-deposit-wallet/spec/openapi/HTTP/Types/JSON.yaml
  lib/customer-deposit-wallet/spec/openapi/index.html
Labels: Deposit

#4508 [ADP-3332] Update E2E instructions
  .github/workflows/e2e-docker.yml
  .github/workflows/e2e-linux.yml
  .github/workflows/e2e-macos.yml
  .github/workflows/e2e-windows.yml
  scripts/gh/fetch-preprod-snapshot.sh
  test/e2e/state/configs/preprod
  test/e2e/state/configs/preprod/alonzo-genesis.json
  test/e2e/state/configs/preprod/byron-genesis.json
  test/e2e/state/configs/preprod/config.json
  test/e2e/state/configs/preprod/conway-genesis.json
  test/e2e/state/configs/preprod/db-sync-config.json
  test/e2e/state/configs/preprod/shelley-genesis.json
  test/e2e/state/configs/preprod/submit-api-config.json
  test/e2e/state/configs/preprod/topology.json
Labels: CI, Conway

#4511 Revert to using deprecated `Shelley.evaluateTransactionFee` call
  lib/balance-tx/lib/internal/Internal/Cardano/Write/Tx.hs
  lib/balance-tx/test/data/balanceTx/1ada-payment/golden
  lib/balance-tx/test/data/balanceTx/delegate/golden
  lib/balance-tx/test/data/balanceTx/pingPong_1/golden
  lib/balance-tx/test/data/balanceTx/pingPong_2/golden
Labels: Conway

#4514 [ADP-3332] Release v2024-03-27
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  specifications/api/swagger.yaml
Labels: Conway
