Repository cardano-foundation/cardano-wallet, pull requests merged in 2025-03, with the labels that each got.

#5021 Document restoration mode in more details
  specifications/api/swagger.yaml
Labels: Docs

#5022 Decrease severity for frequent database query
  lib/wallet/src/Cardano/Wallet/DB/Layer.hs
Labels: Improvement

#5026 Fix artifacts retrieval in release pipeline
  scripts/buildkite/release/push-artifacts.sh
  scripts/buildkite/release/push-to-dockerhub.sh
Labels: Bug, CI, Release

#5027 Fix release notes harvesting
  scripts/buildkite/release/make_changelog.sh
Labels: Bug, CI, Release

#5029 Constrains all cardano lib dependencies via script
  cabal.project
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/exe/cardano-wallet-exe.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  nix/haskell.nix
  scripts/bump-constraints.sh
Labels: Dependencies, Node

#5030 Release v2025-03-04
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/delta-chain/delta-chain.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/exe/cardano-wallet-exe.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
  run/common/docker/run.sh
  scripts/buildkite/main/ruby-e2e.sh
  specifications/api/swagger.yaml
Labels: Release

#5038 Remove deposit wallet discrimination in the UI
  lib/ui/cardano-wallet-ui.cabal
  lib/ui/src/common/Cardano/Wallet/UI/Common/Html/Pages/Wallet.hs
  lib/ui/src/common/Cardano/Wallet/UI/Type.hs
  lib/ui/src/shelley/Cardano/Wallet/UI/Shelley/Html/Pages/Page.hs
  lib/ui/src/shelley/Cardano/Wallet/UI/Shelley/Html/Pages/Wallets.hs
Labels: Deposit, UI

#5043 Enforce cabal-fmt on all libraries under lib
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/application/cardano-wallet-application.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/delta-chain/delta-chain.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/delta-types/delta-types.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/numeric/cardano-numeric.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet/cardano-wallet.cabal
  scripts/buildkite/main/check-code-format.sh
  scripts/bump-constraints.sh
Labels: Improvement

#5046 Substitute cryptonite with crypton
  cabal.project
  flake.nix
  justfile
  lib/application-tls/cardano-wallet-application-tls.cabal
  lib/application-tls/lib/Cardano/X509/Configuration.hs
  lib/application-tls/lib/Data/X509/Extra.hs
  lib/application-tls/test/Cardano/Wallet/Application/TlsSpec.hs
  lib/local-cluster/local-cluster.cabal
  lib/unit/cardano-wallet-unit.cabal
Labels: Improvement

#5052 Fix CI nix sync steps timeout issues
  .buildkite/pipeline.yml
  run/common/nix/run.sh
Labels: CI

#5050 Enforce new line at the end of textual files
  .buildkite/pipeline.yml
  configs/cardano/refresh.sh
  configs/cardano/sanchonet/download.sh
  docs/site/src/index.md
  docs/site/src/user/common-use-cases/delegation.md
  docs/site/src/user/security.md
  lib/delta-types/README.md
  nix/README.md
  scripts/buildkite/admin/flake.nix
  scripts/buildkite/main/linux-package.sh
  scripts/buildkite/release/openapi-diff.sh
  scripts/buildkite/release/push-to-dockerhub.sh
  scripts/buildkite/release/update-documentation-links.sh
  scripts/enforce-eol.sh
  specifications/Cardano/Wallet/Primitive/Types/DeltaUTxO.md
  specifications/Cardano/Wallet/Submissions/design.md
  specifications/Cardano/Wallet/delegation.md
Labels: CI

#5056 Fix gitrev in version output
  .buildkite/pipeline.yml
  .gitignore
  flake.nix
  justfile
  nix/haskell.nix
  nix/set-git-rev/.envrc
  nix/set-git-rev/cabal.project
  nix/set-git-rev/flake.lock
  nix/set-git-rev/flake.nix
  nix/set-git-rev/justfile
  nix/set-git-rev/nix/project.nix
  nix/set-git-rev/set-git-rev.cabal
  nix/set-git-rev/set-git-rev.nix
  nix/set-git-rev/src/set-git-rev.hs
  scripts/buildkite/main/git-revision.sh
Labels: Improvement

#5047 Run release triggered main pipeline integration tests at concurrency 1
  .buildkite/pipeline.yml
  justfile
  scripts/buildkite/release/generate-trigger.sh
Labels: CI

#5057 Fix nigthly tagging
  scripts/buildkite/release/push-tag.sh
Labels: CI

#5031 Bump cardano dependencies to match node to 10.2.1
  .buildkite/pipeline.yml
  README.md
  cabal.project
  configs/cardano/mainnet/config.json
  configs/cardano/preview/config.json
  configs/cardano/preview/download.sh
  flake.lock
  flake.nix
  justfile
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/balance-tx/lib/internal/Internal/Cardano/Write/Tx/Sign.hs
  lib/balance-tx/test/spec/Internal/Cardano/Write/Tx/BalanceSpec.hs
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/cardano-api-extra/lib/Cardano/Api/Gen.hs
  lib/delta-chain/delta-chain.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/integration/configs/cardano/preprod/config.json
  lib/integration/scenarios/Test/Integration/Scenario/API/Shared/Transactions.hs
  lib/integration/scenarios/Test/Integration/Scenario/API/Shelley/TransactionsNew.hs
  lib/local-cluster/lib/Cardano/Wallet/Launch/Cluster/ConfiguredPool.hs
  lib/local-cluster/local-cluster.cabal
  lib/local-cluster/test/data/cluster-configs/node-config.json
  lib/local-cluster/test/data/cluster-configs/template/config.json
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/network-layer/src/Cardano/Wallet/Network/Implementation.hs
  lib/network-layer/src/Cardano/Wallet/Network/Implementation/Ouroboros.hs
  lib/primitive/cardano-wallet-primitive.cabal
  lib/primitive/lib/Cardano/Wallet/Primitive/Ledger/Shelley.hs
  lib/unit/cardano-wallet-unit.cabal
  lib/unit/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs
  lib/wallet/cardano-wallet.cabal
  lib/wallet/src/Cardano/Wallet.hs
  lib/wallet/src/Cardano/Wallet/Shelley/Transaction.hs
  nix/haskell.nix
  nix/overlays/basement.nix
  nix/overlays/cardano-deployments.nix
  nix/release-package.nix
  nix/rewrite-libs/.envrc
  nix/rewrite-libs/flake.lock
  nix/rewrite-libs/flake.nix
  nix/rewrite-libs/justfile
  nix/rewrite-libs/nix/project.nix
  nix/rewrite-libs/result
  nix/rewrite-libs/rewrite-libs.cabal
  nix/rewrite-libs/rewrite-libs.nix
  nix/rewrite-libs/src/rewrite-libs.hs
  scripts/buildkite/release/push-artifacts.sh
  scripts/bump-constraints.sh
  scripts/release-candidate.sh
  scripts/start-10.2.1.sh
Labels: Release, Node
