Repository cardano-foundation/cardano-wallet, pull requests merged in 2025-01, with the labels that each got.

#4898 [#4896] Migration of windows unit tests to buildkite
  .buildkite/pipeline.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/windows.yml
Labels: CI

#4910 Release v2025-01-07
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/delta-chain/delta-chain.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/delta-types/delta-types.cabal
  lib/exe/cardano-wallet-exe.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet-e2e/cardano-wallet-e2e.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
  run/common/docker/run.sh
  scripts/buildkite/main/linux-e2e.sh
  scripts/buildkite/main/macos-silicon-e2e.sh
  specifications/api/swagger.yaml
Labels: Release

#4912 Fix update documentation links script
  scripts/buildkite/release/update-documentation-links.sh
Labels: CI, Release

#4913 Make it possible to run run scripts in nixos
  configs/cardano/mainnet/download.sh
  configs/cardano/preprod/download.sh
  configs/cardano/preview/download.sh
  configs/cardano/private/download.sh
  configs/cardano/refresh.sh
  configs/cardano/sanchonet/download.sh
  run/common/docker/run.sh
  scripts/buildkite/main/attic-cache.sh
  scripts/buildkite/main/docker-build.sh
  test/e2e/fixtures/create-wallets.sh
Labels: Improvement, CI

#4914 Bump cardano-node version to 10.1.4
  cabal.project
  flake.lock
  flake.nix
Labels: Node

#4923 Bump all refs to node 10.1.3 to 10.1.4
  README.md
  justfile
  run/common/docker/run.sh
  scripts/buildkite/main/docker-smoke-test.sh
  scripts/buildkite/release/docker-smoke-test.sh
  scripts/release-candidate.sh
  test/e2e/README.md
  test/e2e/docker_compose.sh
Labels: Node

#4922 Fix mithril download preprod instructions
  scripts/buildkite/admin/refresh-preprod-snapshot.sh
Labels: Bug, CI

#4927 Bump wallet version to 2025.1.9
  README.md
  lib/address-derivation-discovery/address-derivation-discovery.cabal
  lib/api/cardano-wallet-api.cabal
  lib/application-extras/cardano-wallet-application-extras.cabal
  lib/balance-tx/cardano-balance-tx.cabal
  lib/benchmarks/cardano-wallet-benchmarks.cabal
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/cardano-api-extra/cardano-api-extra.cabal
  lib/coin-selection/cardano-coin-selection.cabal
  lib/crypto-primitives/crypto-primitives.cabal
  lib/customer-deposit-wallet/customer-deposit-wallet.cabal
  lib/delta-chain/delta-chain.cabal
  lib/delta-store/delta-store.cabal
  lib/delta-table/delta-table.cabal
  lib/delta-types/delta-types.cabal
  lib/exe/cardano-wallet-exe.cabal
  lib/faucet/faucet.cabal
  lib/integration/cardano-wallet-integration.cabal
  lib/iohk-monitoring-extra/iohk-monitoring-extra.cabal
  lib/launcher/cardano-wallet-launcher.cabal
  lib/local-cluster/local-cluster.cabal
  lib/network-layer/cardano-wallet-network-layer.cabal
  lib/primitive/cardano-wallet-primitive.cabal
  lib/secrets/cardano-wallet-secrets.cabal
  lib/std-gen-seed/std-gen-seed.cabal
  lib/temporary-extra/temporary-extra.cabal
  lib/test-utils/cardano-wallet-test-utils.cabal
  lib/text-class/text-class.cabal
  lib/ui/cardano-wallet-ui.cabal
  lib/unit/cardano-wallet-unit.cabal
  lib/wai-middleware-logging/wai-middleware-logging.cabal
  lib/wallet-benchmarks/cardano-wallet-blackbox-benchmarks.cabal
  lib/wallet-e2e/cardano-wallet-e2e.cabal
  lib/wallet/cardano-wallet.cabal
  prototypes/light-mode-test/light-mode-test.cabal
  run/common/docker/run.sh
  scripts/buildkite/main/linux-e2e.sh
  scripts/buildkite/main/macos-silicon-e2e.sh
  specifications/api/swagger.yaml
Labels: Release

#4941 Update release signatures and maintainers list
  MAINTAINERS.md
  scripts/buildkite/release/release-template.md
Labels: Release, Docs

#4936 Separate test from nightly tag in the assets
  .buildkite/pipeline.yml
  .buildkite/release.yml
  scripts/buildkite/release/push-artifacts.sh
  scripts/buildkite/release/push-release.sh
  scripts/buildkite/release/push-tag.sh
  scripts/buildkite/release/push-to-bump.sh
  scripts/buildkite/release/release-candidate.sh
Labels: Improvement, CI, Release

#4942 Remove tag-release-candidate script
  scripts/buildkite/main/tag-release-candidate.sh
Labels: Improvement, Release

#4945 Add `waitForChange` in latency bench
  lib/benchmarks/exe/latency-bench.hs
Labels: CI

#4951 Fix docker image tag naming in case of non-release branches
  .buildkite/pipeline.yml
  flake.nix
  nix/docker.nix
  scripts/buildkite/main/docker-build.sh
  scripts/buildkite/main/docker-smoke-test.sh
  scripts/buildkite/release/docker-build.sh
  scripts/buildkite/release/docker-smoke-test.sh
  scripts/buildkite/release/openapi-diff.sh
Labels: Improvement, CI

#4955 Add a delete-logs exe in buildkite lib
  lib/benchmarks/exe/benchmark-history.hs
  lib/buildkite/cardano-wallet-buildkite.cabal
  lib/buildkite/exe/delete-logs.hs
  lib/buildkite/src/Buildkite/API.hs
  lib/buildkite/src/Buildkite/Client.hs
  lib/buildkite/src/Buildkite/Connection.hs
  scripts/buildkite/admin/delete-logs.hs
Labels: Improvement, CI

#4954 Improve ruby E2E scripts
  .buildkite/pipeline.yml
  .github/workflows/publish.yml
  flake.lock
  flake.nix
  justfile
  nix/haskell.nix
  scripts/buildkite/main/linux-e2e.sh
  scripts/buildkite/main/macos-silicon-e2e.sh
  scripts/buildkite/main/ruby-e2e.sh
  scripts/buildkite/release/release-candidate.sh
  test/e2e/flake.lock
  test/e2e/flake.nix
Labels: Improvement, CI, Release

#4956 Fix release pipeline
  scripts/buildkite/release/openapi-diff.sh
  scripts/buildkite/release/release-candidate.sh
Labels: CI, Release
